### ISSUE TITLE
Start/Stop Music

### ISSUE THREAD

**Issue by cmacollins82** [james1236/buzzer_music#11]
Is there a way to start stop the music based on an input condition? I have moved the print(mysong.tick()) to a def. This works but when the input is off the last tone is played constantly. How can I stop this?

def music():
    print(mySong.tick())
    sleep(0.04)  

while True:
    if switch1.value()==True:
        led.value(1)
        print("Motion Detected")
        music()
    else:
        led.value(0)

**Comment by james1236** [comment]
Hi, I think `mySong.stop()` and `mySong.resume()` will work
