### ISSUE TITLE
Testing without physical hardware

### ISSUE THREAD

**Issue by michaelachrisco** [james1236/buzzer_music#12]
I went back on this project in time for the holidays. I wanted to test out the electronics without bread-boarding the whole thing again. Not a huge deal, but im being lazy :) 

I created a couple of rough simulated hardware designs that might help others that want to test:
With one buzzer: https://wokwi.com/projects/384398375777186817
With multiple buzzers: https://wokwi.com/projects/384399549451499521

Looks like the hardest part is the actual sound coming out. But that is kinda to be expected given the emulation. But it still sounds pretty good regardless.

**Comment by michaelachrisco** [comment]
Also I cant believe it but they have their own CI: https://docs.wokwi.com/wokwi-ci/getting-started thats kinda wild, you can test hardware/software together in one big package like that.

**Comment by james1236** [comment]
Such amazing software! I added those demos to the README, thank you! Looking forward to what you'll make this year 😄

**Comment by michaelachrisco** [comment]
Glad you like it. Awesome job sprucing those up. Its pretty easy to work with (easier than the breadboard and thats not terrible either).
