### ISSUE TITLE
[help] Issues using rpi 4b

### ISSUE THREAD

**Issue by BorbTheBird** [james1236/buzzer_music#14]
I tried running this on rpi4b 8gb model and after setting it up to pin 16 ran the example which opened a console which just read "true" over and over and played the buzzer for about 2 seconds before the pi just restarted itself. What am I doing wrong?

edit: got it working with an esp32 the only limitation with that is the absolutely tiny amount of memory

**Comment by james1236** [comment]
Nice! I think the Pi may have restarted because of a wiring short between power and ground.

If there's any code you can share specific to getting it working on the ESP32, it would be great if we could put that in the README

**Comment by BorbTheBird** [comment]
Esp32 setup is same as the pico, just need to install micropython interpreter and upload buzzer_music.py as well as the actual music itself. The only issue is the small amount of memory which the program tries to load all of it at once which I have tried implementing a system that reads as it goes but have been unsuccessful.

with the pi I will try some different arrangements since I'm pretty sure it is wired correctly as it works with the esp
Edit: The pi worked, the issue was I had this argon fan hat thing on, and it was just breaking the gpio for some reason however all of the notes are out of tune and messed up for some reason
